# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permiflow < Formula
  desc "Permiflow is a Kubernetes RBAC scanning tool"
  homepage "https://github.com/tutran-se/permiflow"
  version "0.7.2"

  on_macos do
    url "https://github.com/tutran-se/permiflow/releases/download/v0.7.2/permiflow_0.7.2_darwin_amd64.tar.gz"
    sha256 "4e545d0955961a440b2372a1123db29c379587176ff59408febee8b7252ab148"

    def install
      bin.install "permiflow"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Permiflow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tutran-se/permiflow/releases/download/v0.7.2/permiflow_0.7.2_linux_amd64.tar.gz"
        sha256 "fdf567a3cc758c8130b267f297abbdefeeeb9f0555124b827dff03b3450b9cc1"

        def install
          bin.install "permiflow"
        end
      end
    end
  end

  test do
    system "#{bin}/permiflow --version"
  end
end
