# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permiflow < Formula
  desc "Permiflow is a Kubernetes RBAC scanning tool"
  homepage "https://github.com/tutran-se/permiflow"
  version "0.4.0"

  on_macos do
    url "https://github.com/tutran-se/permiflow/releases/download/v0.4.0/permiflow_0.4.0_darwin_amd64.tar.gz"
    sha256 "da69ae63304f25f7fbbfc3e1cca5d3962b639be4d80c5cfac6c5cdfab5673a6b"

    def install
      bin.install "permiflow"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Permiflow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tutran-se/permiflow/releases/download/v0.4.0/permiflow_0.4.0_linux_amd64.tar.gz"
        sha256 "54aca18979fbd4f0604dd9bc3c4bb65cd672665421717b7822e6b1a32af23ff2"

        def install
          bin.install "permiflow"
        end
      end
    end
  end

  test do
    system "#{bin}/permiflow --version"
  end
end
