# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permiflow < Formula
  desc "Permiflow is a Kubernetes RBAC scanning tool"
  homepage "https://github.com/tutran-se/permiflow"
  version "0.5.0"

  on_macos do
    url "https://github.com/tutran-se/permiflow/releases/download/v0.5.0/permiflow_0.5.0_darwin_amd64.tar.gz"
    sha256 "b5e1667d517ba47fe3c4eed6ab6a76b3495a05b972552028874ee1e37a98f008"

    def install
      bin.install "permiflow"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Permiflow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tutran-se/permiflow/releases/download/v0.5.0/permiflow_0.5.0_linux_amd64.tar.gz"
        sha256 "52623d700333a847c25bff3ffe96fa823e905c5e580c6a8a7ccd80caf1dddc27"

        def install
          bin.install "permiflow"
        end
      end
    end
  end

  test do
    system "#{bin}/permiflow --version"
  end
end
